# Generated by Django 5.1.1 on 2024-10-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='garnish',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drink',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drink',
            name='instructions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
