# Generated by Django 5.1.1 on 2024-10-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_drink_garnish_alter_drink_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='img_url',
            field=models.URLField(max_length=300),
        ),
    ]
