# Generated by Django 5.1.1 on 2024-10-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_drink_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='img_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
