# Generated by Django 5.1.1 on 2024-10-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_drink_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='garnish',
        ),
    ]
