# Generated by Django 5.1.1 on 2024-10-17 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_userbar_drink_bar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='bar',
            field=models.ManyToManyField(related_name='drinks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks_contributed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserBar',
        ),
    ]
